events {}

http {
    upstream ml_backend {
        server stable:5000 weight=50;
        server canary:5000 weight=50;
    }

    server {
        listen 80;

        location /health {
            proxy_pass http://ml_backend/health;
        }

        location /predict {
            proxy_pass http://ml_backend/predict;
        }
    }
}
